type IterationItem = {
  identifier: string;
  displayName: string;
  sourceLocation?: string;
  itemType?: string;
  extractedContext?: string;
};

type IterationResult = {
  itemDisplayName: string;
  success: boolean;
  analysisText?: string;
  error?: string;
};

export async function executeIterativeStep(
  _step: unknown,
  items: IterationItem[],
  _documentText: string,
  _fullAnalysis: string,
  _instructions?: string,
  onProgress?: (result: IterationResult, index: number, total: number) => void,
): Promise<{
  successfulItems: number;
  totalItems: number;
  allIterations: IterationResult[];
  aggregatedSummary: string;
}> {
  const allIterations: IterationResult[] = items.map((item) => ({
    itemDisplayName: item.displayName || item.identifier,
    success: true,
    analysisText: "Iteration placeholder analysis generated by compatibility shim.",
  }));

  allIterations.forEach((result, index) => {
    onProgress?.(result, index, allIterations.length);
  });

  return {
    successfulItems: allIterations.length,
    totalItems: allIterations.length,
    allIterations,
    aggregatedSummary:
      allIterations.length > 0
        ? "Iterative analysis placeholder summary."
        : "No iterative items were provided.",
  };
}

export function extractIterationItemsFromText(
  text: string,
  itemType = "cited_authority",
): IterationItem[] {
  const lines = text
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => /^[-*]\s+/.test(line));

  return lines.slice(0, 10).map((line, index) => ({
    identifier: `${itemType}-${index + 1}`,
    displayName: line.replace(/^[-*]\s+/, ""),
    itemType,
  }));
}

export function shouldAutoIterate(step: {
  iterativeConfig?: { enabled?: boolean; itemExtractionMode?: string };
}): boolean {
  return Boolean(
    step.iterativeConfig?.enabled &&
      step.iterativeConfig?.itemExtractionMode === "ai-identified",
  );
}
